### ISSUE TITLE
Finalize Heroku Button

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-rails-webpacker-example#11]
A few things:

- [x] Currently I get an error when deploying that says app.json is invalid due to the name being too long.
- [x] We need to add the honeybadger addong to the manifest. That will automatically configure the `HONEYBADGER_API_KEY` environment variable.
- [x] Is `GIT_COMMIT` a required field? If so, can we add it and default it to "master" ? That way, the only required config option which must be entered manually is the `ASSETS_URL`.
- [x] Update the instructions under "Quick Start" to just say how to configure the ASSETS_URL rather than pointing to the 12-factor section.

**Comment by monde** [comment]
@joshuap `GIT_COMMIT` is not required, it's just some flare I added to the example. Should I get rid of setting the revision parameter on the plugin setup and thus the need to give `GIT_COMMIT` as an example?

**Comment by joshuap** [comment]
Nah, we should suggest that `revision` is used, and ideally it should be the SHA of the latest commit. It makes the source mapping more accurate.

**Comment by joshuap** [comment]
It's fine to just leave it out in the Heroku app.json
